project:
  type: website

website:
  title: "quarto-sorting-repr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - pages/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



